version: "3.9"
services:
  web:
    build: .
    volumes:
      - type: bind
        source: ./functions
        target: /home/deno/functions
      - type: bind
        source: ../core
        target: /home/deno/core
    ports:
      - "8000:9000"
    environment:
      - SERVICE_BASE_DIR=/home/deno/functions/
