version: "3"
services:
  directus:
    container_name: directus
    image: directus/directus:10.10.4
    ports:
      - 8055:8055
    volumes:
      - ./database:/directus/database
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
      - ./snapshots:/directus/snapshots

    network_mode: host
    environment:
      KEY: "replace-with-random-value"
      SECRET: "replace-with-random-value"
      ADMIN_EMAIL: "admin@example.com"
      ADMIN_PASSWORD: "d1r3ctu5"
      DB_CLIENT: "pg"
      DB_HOST: "localhost"
      DB_PORT: "54322"
      DB_DATABASE: "postgres"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
      WEBSOCKETS_ENABLED: "true"
